/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppKomutaRouteImport } from './routes/_app/komuta'
import { Route as AppTriageRouteImport } from './routes/_app/triage'
import { Route as AppOlaylarIndexRouteImport } from './routes/_app/olaylar.index'
import { Route as AppOlaylarIdRouteImport } from './routes/_app/olaylar.$id'
import { Route as AppOlaylarYeniRouteImport } from './routes/_app/olaylar.yeni'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppKomutaRoute = AppKomutaRouteImport.update({
  id: '/komuta',
  path: '/komuta',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppOlaylarIndexRoute = AppOlaylarIndexRouteImport.update({
  id: '/olaylar/',
  path: '/olaylar/',
  getParentRoute: () => AppRoute,
} as any)
const AppOlaylarIdRoute = AppOlaylarIdRouteImport.update({
  id: '/olaylar/$id',
  path: '/olaylar/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOlaylarYeniRoute = AppOlaylarYeniRouteImport.update({
  id: '/olaylar/yeni',
  path: '/olaylar/yeni',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/komuta': typeof AppKomutaRoute
  '/triage': typeof AppTriageRoute
  '/olaylar/$id': typeof AppOlaylarIdRoute
  '/olaylar/yeni': typeof AppOlaylarYeniRoute
  '/olaylar/': typeof AppOlaylarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/komuta': typeof AppKomutaRoute
  '/triage': typeof AppTriageRoute
  '/olaylar/$id': typeof AppOlaylarIdRoute
  '/olaylar/yeni': typeof AppOlaylarYeniRoute
  '/olaylar': typeof AppOlaylarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/_app/komuta': typeof AppKomutaRoute
  '/_app/triage': typeof AppTriageRoute
  '/_app/olaylar/$id': typeof AppOlaylarIdRoute
  '/_app/olaylar/yeni': typeof AppOlaylarYeniRoute
  '/_app/olaylar/': typeof AppOlaylarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    '/' | '/komuta' | '/triage' | '/olaylar/$id' | '/olaylar/yeni' | '/olaylar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    '/' | '/komuta' | '/triage' | '/olaylar/$id' | '/olaylar/yeni' | '/olaylar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/_app/komuta'
    | '/_app/triage'
    | '/_app/olaylar/$id'
    | '/_app/olaylar/yeni'
    | '/_app/olaylar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/komuta': {
      id: '/_app/komuta'
      path: '/komuta'
      fullPath: '/komuta'
      preLoaderRoute: typeof AppKomutaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triage': {
      id: '/_app/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/olaylar/': {
      id: '/_app/olaylar/'
      path: '/olaylar'
      fullPath: '/olaylar/'
      preLoaderRoute: typeof AppOlaylarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/olaylar/$id': {
      id: '/_app/olaylar/$id'
      path: '/olaylar/$id'
      fullPath: '/olaylar/$id'
      preLoaderRoute: typeof AppOlaylarIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/olaylar/yeni': {
      id: '/_app/olaylar/yeni'
      path: '/olaylar/yeni'
      fullPath: '/olaylar/yeni'
      preLoaderRoute: typeof AppOlaylarYeniRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppKomutaRoute: typeof AppKomutaRoute
  AppTriageRoute: typeof AppTriageRoute
  AppOlaylarIdRoute: typeof AppOlaylarIdRoute
  AppOlaylarYeniRoute: typeof AppOlaylarYeniRoute
  AppOlaylarIndexRoute: typeof AppOlaylarIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppKomutaRoute: AppKomutaRoute,
  AppTriageRoute: AppTriageRoute,
  AppOlaylarIdRoute: AppOlaylarIdRoute,
  AppOlaylarYeniRoute: AppOlaylarYeniRoute,
  AppOlaylarIndexRoute: AppOlaylarIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
