/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppRouteImport } from './routes/_app'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AppAiKalitesiRouteImport } from './routes/_app/ai-kalitesi'
import { Route as AppAnalitikRouteImport } from './routes/_app/analitik'
import { Route as AppBilgiRouteImport } from './routes/_app/bilgi'
import { Route as AppDesignSystemRouteImport } from './routes/_app/design-system'
import { Route as AppKomutaRouteImport } from './routes/_app/komuta'
import { Route as AppProblemlerRouteImport } from './routes/_app/problemler'
import { Route as AppTriageRouteImport } from './routes/_app/triage'
import { Route as AppYardimRouteImport } from './routes/_app/yardim'
import { Route as AppYonetimRouteImport } from './routes/_app/yonetim'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AppOlaylarIndexRouteImport } from './routes/_app/olaylar.index'
import { Route as AppOlaylarIdRouteImport } from './routes/_app/olaylar.$id'
import { Route as AppOlaylarYeniRouteImport } from './routes/_app/olaylar.yeni'
import { Route as ApiWebhooksIncidentsRouteImport } from './routes/api.webhooks.incidents'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppAiKalitesiRoute = AppAiKalitesiRouteImport.update({
  id: '/ai-kalitesi',
  path: '/ai-kalitesi',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalitikRoute = AppAnalitikRouteImport.update({
  id: '/analitik',
  path: '/analitik',
  getParentRoute: () => AppRoute,
} as any)
const AppBilgiRoute = AppBilgiRouteImport.update({
  id: '/bilgi',
  path: '/bilgi',
  getParentRoute: () => AppRoute,
} as any)
const AppDesignSystemRoute = AppDesignSystemRouteImport.update({
  id: '/design-system',
  path: '/design-system',
  getParentRoute: () => AppRoute,
} as any)
const AppKomutaRoute = AppKomutaRouteImport.update({
  id: '/komuta',
  path: '/komuta',
  getParentRoute: () => AppRoute,
} as any)
const AppProblemlerRoute = AppProblemlerRouteImport.update({
  id: '/problemler',
  path: '/problemler',
  getParentRoute: () => AppRoute,
} as any)
const AppTriageRoute = AppTriageRouteImport.update({
  id: '/triage',
  path: '/triage',
  getParentRoute: () => AppRoute,
} as any)
const AppYardimRoute = AppYardimRouteImport.update({
  id: '/yardim',
  path: '/yardim',
  getParentRoute: () => AppRoute,
} as any)
const AppYonetimRoute = AppYonetimRouteImport.update({
  id: '/yonetim',
  path: '/yonetim',
  getParentRoute: () => AppRoute,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AppOlaylarIndexRoute = AppOlaylarIndexRouteImport.update({
  id: '/olaylar/',
  path: '/olaylar/',
  getParentRoute: () => AppRoute,
} as any)
const AppOlaylarIdRoute = AppOlaylarIdRouteImport.update({
  id: '/olaylar/$id',
  path: '/olaylar/$id',
  getParentRoute: () => AppRoute,
} as any)
const AppOlaylarYeniRoute = AppOlaylarYeniRouteImport.update({
  id: '/olaylar/yeni',
  path: '/olaylar/yeni',
  getParentRoute: () => AppRoute,
} as any)
const ApiWebhooksIncidentsRoute = ApiWebhooksIncidentsRouteImport.update({
  id: '/api/webhooks/incidents',
  path: '/api/webhooks/incidents',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai-kalitesi': typeof AppAiKalitesiRoute
  '/analitik': typeof AppAnalitikRoute
  '/bilgi': typeof AppBilgiRoute
  '/design-system': typeof AppDesignSystemRoute
  '/komuta': typeof AppKomutaRoute
  '/problemler': typeof AppProblemlerRoute
  '/triage': typeof AppTriageRoute
  '/yardim': typeof AppYardimRoute
  '/yonetim': typeof AppYonetimRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/olaylar/$id': typeof AppOlaylarIdRoute
  '/olaylar/yeni': typeof AppOlaylarYeniRoute
  '/api/webhooks/incidents': typeof ApiWebhooksIncidentsRoute
  '/olaylar/': typeof AppOlaylarIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/ai-kalitesi': typeof AppAiKalitesiRoute
  '/analitik': typeof AppAnalitikRoute
  '/bilgi': typeof AppBilgiRoute
  '/design-system': typeof AppDesignSystemRoute
  '/komuta': typeof AppKomutaRoute
  '/problemler': typeof AppProblemlerRoute
  '/triage': typeof AppTriageRoute
  '/yardim': typeof AppYardimRoute
  '/yonetim': typeof AppYonetimRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/olaylar/$id': typeof AppOlaylarIdRoute
  '/olaylar/yeni': typeof AppOlaylarYeniRoute
  '/api/webhooks/incidents': typeof ApiWebhooksIncidentsRoute
  '/olaylar': typeof AppOlaylarIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/mcp': typeof McpRoute
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/_app/ai-kalitesi': typeof AppAiKalitesiRoute
  '/_app/analitik': typeof AppAnalitikRoute
  '/_app/bilgi': typeof AppBilgiRoute
  '/_app/design-system': typeof AppDesignSystemRoute
  '/_app/komuta': typeof AppKomutaRoute
  '/_app/problemler': typeof AppProblemlerRoute
  '/_app/triage': typeof AppTriageRoute
  '/_app/yardim': typeof AppYardimRoute
  '/_app/yonetim': typeof AppYonetimRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_app/olaylar/$id': typeof AppOlaylarIdRoute
  '/_app/olaylar/yeni': typeof AppOlaylarYeniRoute
  '/api/webhooks/incidents': typeof ApiWebhooksIncidentsRoute
  '/_app/olaylar/': typeof AppOlaylarIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai-kalitesi'
    | '/analitik'
    | '/bilgi'
    | '/design-system'
    | '/komuta'
    | '/problemler'
    | '/triage'
    | '/yardim'
    | '/yonetim'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/olaylar/$id'
    | '/olaylar/yeni'
    | '/api/webhooks/incidents'
    | '/olaylar/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/ai-kalitesi'
    | '/analitik'
    | '/bilgi'
    | '/design-system'
    | '/komuta'
    | '/problemler'
    | '/triage'
    | '/yardim'
    | '/yonetim'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/olaylar/$id'
    | '/olaylar/yeni'
    | '/api/webhooks/incidents'
    | '/olaylar'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/mcp'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/_app/ai-kalitesi'
    | '/_app/analitik'
    | '/_app/bilgi'
    | '/_app/design-system'
    | '/_app/komuta'
    | '/_app/problemler'
    | '/_app/triage'
    | '/_app/yardim'
    | '/_app/yonetim'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_app/olaylar/$id'
    | '/_app/olaylar/yeni'
    | '/api/webhooks/incidents'
    | '/_app/olaylar/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  McpRoute: typeof McpRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiWebhooksIncidentsRoute: typeof ApiWebhooksIncidentsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/ai-kalitesi': {
      id: '/_app/ai-kalitesi'
      path: '/ai-kalitesi'
      fullPath: '/ai-kalitesi'
      preLoaderRoute: typeof AppAiKalitesiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analitik': {
      id: '/_app/analitik'
      path: '/analitik'
      fullPath: '/analitik'
      preLoaderRoute: typeof AppAnalitikRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/bilgi': {
      id: '/_app/bilgi'
      path: '/bilgi'
      fullPath: '/bilgi'
      preLoaderRoute: typeof AppBilgiRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/design-system': {
      id: '/_app/design-system'
      path: '/design-system'
      fullPath: '/design-system'
      preLoaderRoute: typeof AppDesignSystemRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/komuta': {
      id: '/_app/komuta'
      path: '/komuta'
      fullPath: '/komuta'
      preLoaderRoute: typeof AppKomutaRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/problemler': {
      id: '/_app/problemler'
      path: '/problemler'
      fullPath: '/problemler'
      preLoaderRoute: typeof AppProblemlerRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/triage': {
      id: '/_app/triage'
      path: '/triage'
      fullPath: '/triage'
      preLoaderRoute: typeof AppTriageRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yardim': {
      id: '/_app/yardim'
      path: '/yardim'
      fullPath: '/yardim'
      preLoaderRoute: typeof AppYardimRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/yonetim': {
      id: '/_app/yonetim'
      path: '/yonetim'
      fullPath: '/yonetim'
      preLoaderRoute: typeof AppYonetimRouteImport
      parentRoute: typeof AppRoute
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/olaylar/': {
      id: '/_app/olaylar/'
      path: '/olaylar'
      fullPath: '/olaylar/'
      preLoaderRoute: typeof AppOlaylarIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/olaylar/$id': {
      id: '/_app/olaylar/$id'
      path: '/olaylar/$id'
      fullPath: '/olaylar/$id'
      preLoaderRoute: typeof AppOlaylarIdRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/olaylar/yeni': {
      id: '/_app/olaylar/yeni'
      path: '/olaylar/yeni'
      fullPath: '/olaylar/yeni'
      preLoaderRoute: typeof AppOlaylarYeniRouteImport
      parentRoute: typeof AppRoute
    }
    '/api/webhooks/incidents': {
      id: '/api/webhooks/incidents'
      path: '/api/webhooks/incidents'
      fullPath: '/api/webhooks/incidents'
      preLoaderRoute: typeof ApiWebhooksIncidentsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteChildren {
  AppAiKalitesiRoute: typeof AppAiKalitesiRoute
  AppAnalitikRoute: typeof AppAnalitikRoute
  AppBilgiRoute: typeof AppBilgiRoute
  AppDesignSystemRoute: typeof AppDesignSystemRoute
  AppKomutaRoute: typeof AppKomutaRoute
  AppProblemlerRoute: typeof AppProblemlerRoute
  AppTriageRoute: typeof AppTriageRoute
  AppYardimRoute: typeof AppYardimRoute
  AppYonetimRoute: typeof AppYonetimRoute
  AppOlaylarIdRoute: typeof AppOlaylarIdRoute
  AppOlaylarYeniRoute: typeof AppOlaylarYeniRoute
  AppOlaylarIndexRoute: typeof AppOlaylarIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAiKalitesiRoute: AppAiKalitesiRoute,
  AppAnalitikRoute: AppAnalitikRoute,
  AppBilgiRoute: AppBilgiRoute,
  AppDesignSystemRoute: AppDesignSystemRoute,
  AppKomutaRoute: AppKomutaRoute,
  AppProblemlerRoute: AppProblemlerRoute,
  AppTriageRoute: AppTriageRoute,
  AppYardimRoute: AppYardimRoute,
  AppYonetimRoute: AppYonetimRoute,
  AppOlaylarIdRoute: AppOlaylarIdRoute,
  AppOlaylarYeniRoute: AppOlaylarYeniRoute,
  AppOlaylarIndexRoute: AppOlaylarIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  McpRoute: McpRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiWebhooksIncidentsRoute: ApiWebhooksIncidentsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
